sudo: required
services:
  - docker
before_install:
  - gem install bundler --pre
  - docker build -t react-image -f DockerFile.dev .
# script:
#   - docker run react-image npm run test -- --coverage
deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker-prod-test'
  env: 'DockerProdTest-env'
  bucket_name: 'elasticbeanstalk-us-east-2-613477468386'
  bucket_path: 'docker-prod-test'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
